In [1]:
from google.colab import files
uploaded= files.upload()

Saving UpdatedResumeDataSet.csv to UpdatedResumeDataSet.csv


In [2]:
import pandas as pd
df= pd.read_csv('UpdatedResumeDataSet.csv')
df.head()

,Category,Resume
0,Data Science,Skills * Programming Languages: Python (pandas...
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...
2,Data Science,"Areas of Interest Deep Learning, Control Syste..."
3,Data Science,Skills • R • Python • SAP HANA • Table...
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab..."


In [3]:
#DATA PREPROCESSING

In [4]:
df.shape #962 resumes, 2 columns

(962, 2)

In [5]:
df.isnull().sum()

,0
Category,0
Resume,0


In [6]:
df.duplicated().sum()

np.int64(796)

In [7]:
df['Category'].value_counts()

,count
Category,
Java Developer,84
Testing,70
DevOps Engineer,55
Python Developer,48
Web Designing,45
HR,44
Hadoop,42
Sales,40
Data Science,40


In [8]:
df[df.duplicated()].head()

,Category,Resume
10,Data Science,Skills * Programming Languages: Python (pandas...
11,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...
12,Data Science,"Areas of Interest Deep Learning, Control Syste..."
13,Data Science,Skills • R • Python • SAP HANA • Table...
14,Data Science,"Education Details \r\n MCA YMCAUST, Faridab..."


In [9]:
df[df.duplicated(keep=False)].head(20)

,Category,Resume
0,Data Science,Skills * Programming Languages: Python (pandas...
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...
2,Data Science,"Areas of Interest Deep Learning, Control Syste..."
3,Data Science,Skills • R • Python • SAP HANA • Table...
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab..."
5,Data Science,"SKILLS C Basics, IOT, Python, MATLAB, Data Sci..."
6,Data Science,Skills • Python • Tableau • Data Visuali...
7,Data Science,Education Details \r\n B.Tech Rayat and Bahr...
8,Data Science,Personal Skills ➢ Ability to quickly grasp t...
9,Data Science,Expertise − Data and Quantitative Analysis â...


In [10]:
df.iloc[0]['Resume'] == df.iloc[10]['Resume']

True

In [11]:
df.duplicated().sum()

np.int64(796)

In [12]:
df['Resume'].duplicated().sum()

np.int64(796)

In [13]:
print("Before:", df.shape)

df = df.drop_duplicates()

print("After:", df.shape)

Before: (962, 2)
After: (166, 2)


In [14]:
df['Category'].value_counts() #25 categories

,count
Category,
Java Developer,13
Database,11
Advocate,10
HR,10
Data Science,10
Automation Testing,7
DevOps Engineer,7
Testing,7
DotNet Developer,7


In [15]:
df['Resume'].iloc[0]

'Skills * Programming Languages: Python (pandas, numpy, scipy, scikit-learn, matplotlib), Sql, Java, JavaScript/JQuery. * Machine learning: Regression, SVM, Naïve Bayes, KNN, Random Forest, Decision Trees, Boosting techniques, Cluster Analysis, Word Embedding, Sentiment Analysis, Natural Language processing, Dimensionality reduction, Topic Modelling (LDA, NMF), PCA & Neural Nets. * Database Visualizations: Mysql, SqlServer, Cassandra, Hbase, ElasticSearch D3.js, DC.js, Plotly, kibana, matplotlib, ggplot, Tableau. * Others: Regular Expression, HTML, CSS, Angular 6, Logstash, Kafka, Python Flask, Git, Docker, computer vision - Open CV and understanding of Deep learning.Education Details \r\n\r\nData Science Assurance Associate \r\n\r\nData Science Assurance Associate - Ernst & Young LLP\r\nSkill Details \r\nJAVASCRIPT- Exprience - 24 months\r\njQuery- Exprience - 24 months\r\nPython- Exprience - 24 monthsCompany Details \r\ncompany - Ernst & Young LLP\r\ndescription - Fraud Investigatio

In [16]:
df['Resume'].iloc[10]

'TECHNICAL SKILLS â\x80¢ Typewriting â\x80¢ TORA â\x80¢ SPSSEducation Details \r\nJanuary 2017 MBA  Chidambaram, Tamil Nadu SNS College of Engineering\r\nJanuary 2014 HSC   at SAV Higher Secondary School\r\n MBA   SNS College of Engineering\r\n SSLC Finance  at Kamaraj Matriculation School\r\nHR \r\n\r\n\r\nSkill Details \r\nHuman resource, Finance- Exprience - Less than 1 year monthsCompany Details \r\ncompany - \r\ndescription - '

In [17]:
import re

def clean_resume(text):

    text = re.sub(r'\r|\n', ' ', text)

    text = re.sub(r'[^a-zA-Z ]', ' ', text)

    text = re.sub(r'\s+', ' ', text)

    text = text.lower()

    return text

In [18]:
df['cleaned_resume'] = df['Resume'].apply(clean_resume)

In [19]:
print("BEFORE:")
print(df['Resume'].iloc[0])

print("\nAFTER:")
print(df['cleaned_resume'].iloc[0])

BEFORE:
Skills * Programming Languages: Python (pandas, numpy, scipy, scikit-learn, matplotlib), Sql, Java, JavaScript/JQuery. * Machine learning: Regression, SVM, Naïve Bayes, KNN, Random Forest, Decision Trees, Boosting techniques, Cluster Analysis, Word Embedding, Sentiment Analysis, Natural Language processing, Dimensionality reduction, Topic Modelling (LDA, NMF), PCA & Neural Nets. * Database Visualizations: Mysql, SqlServer, Cassandra, Hbase, ElasticSearch D3.js, DC.js, Plotly, kibana, matplotlib, ggplot, Tableau. * Others: Regular Expression, HTML, CSS, Angular 6, Logstash, Kafka, Python Flask, Git, Docker, computer vision - Open CV and understanding of Deep learning.Education Details 

Data Science Assurance Associate 

Data Science Assurance Associate - Ernst & Young LLP
Skill Details 
JAVASCRIPT- Exprience - 24 months
jQuery- Exprience - 24 months
Python- Exprience - 24 monthsCompany Details 
company - Ernst & Young LLP
description - Fraud Investigations and Dispute Services

In [20]:
df.head()

,Category,Resume,cleaned_resume
0,Data Science,Skills * Programming Languages: Python (pandas...,skills programming languages python pandas num...
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,education details may to may b e uit rgpv data...
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",areas of interest deep learning control system...
3,Data Science,Skills • R • Python • SAP HANA • Table...,skills r python sap hana tableau sap hana sql ...
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",education details mca ymcaust faridabad haryan...


In [21]:
#2. CONCERT CATEGORICAL DATA INTO NUMBERS - LABEL ENCODING


In [22]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
df['category_encoded']=le.fit_transform(df['Category'])
df.head()

,Category,Resume,cleaned_resume,category_encoded
0,Data Science,Skills * Programming Languages: Python (pandas...,skills programming languages python pandas num...,6
1,Data Science,Education Details \r\nMay 2013 to May 2017 B.E...,education details may to may b e uit rgpv data...,6
2,Data Science,"Areas of Interest Deep Learning, Control Syste...",areas of interest deep learning control system...,6
3,Data Science,Skills • R • Python • SAP HANA • Table...,skills r python sap hana tableau sap hana sql ...,6
4,Data Science,"Education Details \r\n MCA YMCAUST, Faridab...",education details mca ymcaust faridabad haryan...,6


In [23]:
#VECTORIZATION : TF-IDF

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf= TfidfVectorizer(stop_words='english', max_features=1000)
x= tfidf.fit_transform(df['cleaned_resume'])  #input features
y= df['category_encoded'] #output label / feature

In [25]:
print(x.shape) #166- number of resumes , 3000- number of features (words created by TF-IDF)

(166, 1000)


In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state=42)


In [27]:
print(x_train.shape)
print(x_test.shape)

(132, 1000)
(34, 1000)


In [28]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(x_train,y_train)
y_pred= model.predict(x_test)

In [29]:
#accuracy

from sklearn.metrics import accuracy_score
accuracy= accuracy_score(y_test, y_pred)
print("accuracy: ", accuracy)

accuracy:  0.6470588235294118


In [30]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      0.50      0.67         2
           2       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         3
           5       1.00      1.00      1.00         2
           6       0.50      1.00      0.67         1
           7       0.67      1.00      0.80         2
           8       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         1
          11       1.00      1.00      1.00         1
          12       1.00      0.80      0.89         5
          13       1.00      0.67      0.80         3
          14       1.00      0.50      0.67         2
          15       0.12      1.00      0.22         1
          16       1.00      1.00      1.00         1
          17       1.00      1.00      1.00         1
          18       0.00      0.00      0.00         2
          20       0.00    

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_

In [31]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(y_test, y_pred)
print (cm)

[[2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 4 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 2 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 2 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [32]:
#to check whether our trained model actually works on new data.
sample_resume = """
Python
Machine Learning
SQL
Deep Learning
NLP
TensorFlow
Pandas
"""

In [33]:
sample_resume = clean_resume(sample_resume)

In [34]:
sample_vector = tfidf.transform([sample_resume])

In [35]:
prediction = model.predict(sample_vector)

le.inverse_transform(prediction)

array(['Data Science'], dtype=object)

In [ ]:
#trying more models

In [36]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score
nb= MultinomialNB()
nb.fit(x_train, y_train)
nb_pred= nb.predict(x_test)
print("accuracy score of Multinomial NB:",accuracy_score(y_test, nb_pred) )

accuracy score of Multinomial NB: 0.2647058823529412


In [39]:
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score
svm= LinearSVC()
svm.fit(x_train, y_train)
svm_pred= svm.predict(x_test)
print("accuracy score of SVM:",accuracy_score(y_test, svm_pred) )

accuracy score of SVM: 0.9411764705882353


In [43]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf_model.fit(x_train, y_train)

rf_pred = rf_model.predict(x_test)

rf_acc = accuracy_score(y_test, rf_pred)

print("accuracy score of RANDOM FOREST:",rf_acc )

accuracy score of RANDOM FOREST: 0.7647058823529411
